site_name: Joshua Gray
site_url: https://joshuagray.io/
site_description: Cybersecurity, Cloud, and AI Engineering
site_url: https://joshuagray.io
site_author: Joshua Gray

theme:
  name: material

  palette:
    scheme: slate
    primary: black
    accent: blue

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest

  logo: assets/images/lion-logo.png
  favicon: assets/images/lion-favicon.png

nav:
  - Home: index.md

  - Projects:
      - Overview: projects/index.md
      - Cybersecurity: projects/cybersecurity.md
      - Cloud: projects/cloud.md
      - AI: projects/ai-security.md

  - Resources:
      - Overview: resources/index.md
      - Detection Engineering: resources/detections.md
      - Security Automation: resources/automation.md
      - Architecture Templates: resources/architecture.md
      - Technical Guides: resources/guides.md

  - Contributions: contributions/index.md

  - About: about.md

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

plugins:
  - search
  - social:
      enabled: !ENV [CI, false]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joshua-gray-sec
      name: GitHub

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@joshua_gray_io
      name: YouTube